# Generated by Django 4.0.6 on 2022-09-18 13:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('judging_criteria', models.TextField()),
                ('prize_1', models.IntegerField()),
                ('prize_2', models.IntegerField()),
                ('prize_3', models.IntegerField()),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team')], max_length=11)),
                ('eligible_gender', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10), size=2)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('remarks', models.CharField(max_length=200)),
                ('prize_reveal', models.BooleanField(default=False)),
                ('events', models.ManyToManyField(to='submissions.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_id', models.IntegerField()),
                ('events', models.ManyToManyField(to='submissions.event')),
                ('members', models.ManyToManyField(to='submissions.participant')),
            ],
        ),
    ]
